# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"\x1f\n\x0bTaskRequest\x12\x10\n\x08integers\x18\x01 \x03(\x05\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x42\n\x0fTaskDistributor\x12/\n\x0e\x44istributeTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKREQUEST._serialized_start=14
  _TASKREQUEST._serialized_end=45
  _TASKRESPONSE._serialized_start=47
  _TASKRESPONSE._serialized_end=77
  _TASKDISTRIBUTOR._serialized_start=79
  _TASKDISTRIBUTOR._serialized_end=145
# @@protoc_insertion_point(module_scope)
